.github/workflows/chromatic.yml, .github/workflows/deploy-storybook.yml, package.json, yarn.lock
=> feat: :construction_worker: chromatic ci 추가

.lintstagedrc, package.json, src/components/reusable/Stepper/Stepper.stories.tsx, src/components/reusable/Stepper/Stepper.style.ts, src/components/reusable/Stepper/Stepper.tsx, src/components/reusable/Stepper/Stepper.types.ts, src/components/reusable/Stepper/index.ts, yarn.lock
- 현재 진행상태를 나타내는 Stepper component를 작성했습니다.
- 타입체킹을 따로 하지 않고 푸시를 할 경우 ci서버에서 타입에러로 빌드 실패하는 현상을 방지하기 위해 커밋 전 타입체킹을 하는 커맨드를 추가했습니다
<-- 구현 내용 및 작업 했던 내역 -->
[스토리북](https://62b83eaee7b099045d81e168-xgxlnfcguf.chromatic.com](https://62b83eaee7b099045d81e168-rxtmvkubij.chromatic.com)
=> ✨ feat: steeper component 작성

.eslintignore, package.json, src/scripts/create-component.ts, tsconfig.json, yarn.lock
- ts-node 설치
- 컴포넌트 하나를 생성하는데 공수를 줄이기 위해 기본 폴더들과 코드들을 생성해줍니다.
- 사용방법: `yarn create-component [컴포넌트명] [컴포넌트가 위치할 Path명]`;
- ex) `yarn create-component Button src/components/reusable`
=> ✨ feat: 컴포넌트 생성 스크립트 추가

src/pages/rooms/[id]/detail.styles.ts, src/shared/components/ModalLayout/ModalLayout.styles.ts, src/themes/index.ts, src/themes/theme.ts, src/themes/zIndex/index.ts, src/themes/zIndex/theme.ts, src/themes/zIndex/types.ts
- z-index 테마를 추가했습니다(header, modal, alert, bottom-sheet)
- 추후에 z-index가 필요한 컴포넌트가 있으면 여기에 zindex값을 추가하면 될것 같습니다.
=> feat: :sparkles: feat: zindex 테마 추가

.vscode/settings.json
- conventional commit시 불필요한 prompt(커밋 바디, 커밋 푸터, 커밋 스코프 물어보는 프롬트) 안나오도록 설정파일 변경
- conventional commit시 eslint, type 체크를 할 수 있도록 물어보는 prompt나오도록 변경
=> chore: :construction_worker: conventional commit 불필요한 promt안나오도록 변경, ci체크하는 prompt나오도록 변경

src/features/chat/components/LinkManageListItem/LinkManageListItem.stories.tsx, src/features/chat/components/LinkManageListItem/LinkManageListItem.styles.ts, src/features/chat/components/LinkManageListItem/LinkManageListItem.tsx, src/features/chat/components/LinkManageListItem/LinkManageListItem.types.ts, src/features/chat/components/LinkManageListItem/index.ts, src/shared/components/Checkbox/Checkbox.types.ts
LinkManageListItem 추가
- [스토리북](https://62b83eaee7b099045d81e168-oqgeodxpjh.chromatic.com/?path=/story/components-chat-linkmanagelistitem--%ED%8E%B8%EC%A7%91-%EB%AA%A8%EB%93%9C)
=> feat: :sparkles: LinkManageListItem 추가

src/features/chat/components/ImageManageListItem/ImageManageListItem.stories.tsx, src/features/chat/components/ImageManageListItem/ImageManageListItem.styles.ts, src/features/chat/components/ImageManageListItem/ImageManageListItem.tsx, src/features/chat/components/ImageManageListItem/ImageManageListItem.types.ts, src/features/chat/components/ImageManageListItem/index.ts, src/shared/components/Checkbox/Checkbox.types.ts
ImageManageListItem 컴포넌트 추가 (읽기모드, 편집모드)
- [스토리북](https://62b83eaee7b099045d81e168-smobmuezhf.chromatic.com/?path=/story/components-chat-imagemanagelistitem--%ED%8E%B8%EC%A7%91-%EB%AA%A8%EB%93%9C)
=> feat: :sparkles: ImageManageListItem 컴포넌트 추가

src/pages/rooms/[id]/images-and-videos/images-and-videos.styles.ts, src/pages/rooms/[id]/images-and-videos/index.page.tsx, src/shared/components/BackButton/BackButton.styles.ts, src/shared/components/BackButton/BackButton.tsx, src/shared/components/BackButton/BackButton.types.ts, src/shared/components/BackButton/index.ts, src/shared/components/Header/Header.stories.tsx, src/shared/components/Header/Header.styles.ts, src/shared/components/Header/Header.tsx, src/shared/components/Header/Header.types.ts
- leftIconName, onLeftIconClick -> leftButtons prop으로 수정
- rightIconName, onRightIconClick -> rightButtons 로 수정
- hasBottomLine prop 추가
- BackButton 컴포넌트로 분리
- 사진 모아보기 페이지 mode==='edit'일때 체크 대신 '취소'텍스트로 수정
- [스토리북](https://62b83eaee7b099045d81e168-gjctvtwooz.chromatic.com/?path=/story/shared-components-header--%EC%95%84%EC%9D%B4%EC%BD%98%EC%9D%B4-%ED%85%8D%EC%8A%A4%ED%8A%B8%EC%9D%BC-%EB%95%8C)
=> refactor: ♻️ Header 리팩토링

.storybook/preview.js, package.json, src/pages/_app.page.tsx, src/shared/components/MainLayout/MainLayout.tsx, src/shared/components/ToastContainer/ToastContainer.stories.tsx, src/shared/components/ToastContainer/ToastContainer.tsx, src/shared/components/ToastContainer/index.ts, src/shared/utils/toast.tsx, src/themes/GlobalStyle.tsx, yarn.lock
react-toastify 적용 및 커스텀
[스토리북](https://62b83eaee7b099045d81e168-pbigyyqaja.chromatic.com/?path=/story/shared-components-toastcontainer--default)
=> feat: :sparkles: react-toastify 적용 및 커스텀

package.json, src/features/chat/components/LinkManageListItem/LinkManageListItem.styles.ts, src/features/chat/components/LinkManageListItem/LinkManageListItem.tsx, src/pages/rooms/[id]/images-and-videos/images-and-videos.styles.ts, src/pages/rooms/[id]/images-and-videos/images-and-videos.types.ts, src/pages/rooms/[id]/images-and-videos/index.page.tsx, src/pages/rooms/[id]/links/index.page.tsx, src/pages/rooms/[id]/links/links.stories.tsx, src/pages/rooms/[id]/links/links.styles.ts, src/pages/rooms/[id]/links/links.types.ts, src/shared/components/Header/Header.styles.ts
- 링크 모아보기 페이지 마크업 추가
- [스토리북](https://62b83eaee7b099045d81e168-zplawmjuzm.chromatic.com/?path=/story/pages-rooms-detail-linkmanagelist--default)
- 사진 모아보기 페이지 깨짐 수정
=> feat: ✨ 링크 모아보기 페이지 마크업 추가

src/features/room/api/useDeleteMemoRoomMutation.tsx, src/features/room/api/useMemoRoomQuery.tsx, src/features/room/api/useUpdateMemoRoomMutation.tsx, src/pages/rooms/[id]/setting/index.page.tsx, src/pages/rooms/[id]/setting/setting.styles.ts, src/pages/rooms/[id]/setting/setting.types.ts, src/shared/types/api/memoRooms.ts
=> feat: ✨ 룸 설정 페이지 api 연동

.vscode/settings.json, Dockerfile, next.config.js, package.json, yarn.lock
- dockerfile을 추가했습니다
- multi stage빌드를 통해 도커 이미지 사이즈를 최대한 줄였습니다.
- expermental인 standalone옵션을 추가해서 실행 파일 크기를 최소화했습니다.
=> ci: :construction_worker: dockerfile 작성

src/pages/rooms/[id]/setting/index.page.tsx, src/pages/rooms/index.page.tsx, src/shared/components/Button/Button.stories.tsx, src/shared/components/Button/Button.styles.ts, src/shared/components/Button/Button.types.ts, src/shared/components/ConfirmModal/ConfirmModal.tsx, src/shared/components/ConfirmModal/ConfirmModal.types.ts, src/shared/components/GlobalConfirmModal/GlobalConfirmModal.tsx, src/shared/contexts/ModalReducerContext/modalReducer.types.ts, src/shared/hooks/useConfirm.ts
* Button 컴포넌트 'danger'  variant 값 추가
* ConfirmModal 컴포넌트 okVariant prop 추가
=> feat: Button, ConfirmModal 컴포넌트 'danger' 타입 적용

src/features/room/components/RoomMemoForm/RoomMemoForm.tsx, src/pages/_app.page.tsx, src/pages/rooms/index.page.tsx, src/pages/test/index.page.tsx, src/shared/components/KeyboardFloatingLayout/KeyboardFloatingLayout.tsx, src/shared/configs/webview/nativeBridge.ts, src/shared/configs/webview/nativeMessageSender.ts, src/shared/configs/webview/types.ts, src/shared/hooks/useOS.ts, src/shared/utils/getOS.ts
웹뷰에서 갤러리 버튼을 누르면 갤러리를 띄우고, 카메라 버튼을 누르면 카메라 여는 기능 구현
* NativeBridge 클래스에서 message를 의미하는 네이밍이 각각 req, params로 제각각이라서 message로 통일했습니다.
* NativeToWebCallbackMessageError 타입 추가
=> feat: uploadImage 웹뷰 브릿지 구현

.env.example, .gitignore, global.d.ts, src/shared/configs/axios/index.ts
=> feat: :sparkles: add env

src/features/chat/api/useCreateChatMutation.ts, src/features/chat/components/Chat/Chat.types.ts, src/features/room/components/RoomMemoForm/RoomMemoForm.tsx, src/features/room/hooks/useMemoForm.tsx, src/shared/types/api/chat.ts, src/shared/types/chat.ts
=> feat: :sparkles: 채팅 생성 api 연동

src/features/settings/components/SettingDetailMenu/SettingDetailMenu.styles.ts, src/pages/settings/settings.styles.ts, src/shared/styles/GlobalStyle.tsx
=> Refactor: setting페이지 스타일링 수정

.eslintrc, package.json, src/features/chat/components/ChatListEmpty/ChatListEmpty.styles.ts, src/features/chat/components/ChatListEmpty/ChatListEmpty.tsx, src/features/chat/components/ImageManageListItem/ImageManageListItem.tsx, src/features/room/components/RoomListEmpty/RoomListEmpty.styles.ts, src/features/room/components/RoomListEmpty/RoomListEmpty.tsx, src/features/room/components/RoomListItem/RoomListItem.stories.tsx, src/features/settings/components/SettingDetailMenu/SettingDetailMenu.styles.ts, src/features/settings/components/SettingDetailMenu/SettingDetailMenu.tsx, src/pages/404/404.styles.ts, src/pages/404/index.page.tsx, src/pages/home/home.styles.ts, src/pages/home/index.page.tsx, src/pages/rooms/[roomId]/setting/index.page.tsx, src/pages/rooms/[roomId]/setting/setting.styles.ts, src/pages/rooms/index.page.tsx, src/pages/settings/account/account.styles.ts, src/pages/settings/account/index.page.tsx, src/shared/components/Button/Button.styles.ts, src/shared/components/Button/Button.tsx, src/shared/components/Button/Button.types.ts, yarn.lock
- next 13으로 업데이트
- next/link, next/image 변경된 스펙 대응
https://nextjs.org/docs/upgrading#upgrading-from-12-to-13
=> feat: next 13 마이그레이션

src/features/chat/components/ChatList/ChatList.tsx, src/pages/rooms/[roomId]/chats/index.page.tsx, src/pages/rooms/index.page.tsx, src/shared/configs/axios/index.ts
=> feat: :zap: 채팅 목록 페이지 ssr 적용

src/features/auth/api/useVerifications.tsx, src/features/auth/hooks/useAuth.tsx, src/features/chat/api/useChatsInfiniteQuery.ts, src/pages/rooms/[roomId]/chats/index.page.tsx, src/pages/signin/index.page.tsx
- GET /rooms/36/chats api 응답이 변경되어 해당부분 코드를 수정했습니다.
- 데이터자체가 안나와 일단 임의로 수정했는데 한번 확인 부탁드립니다.
=> fix: :bug: api응답이 변경됨에 따라 chat infiniteQuery변경

package.json, src/features/chat/api/useChatsInfiniteQuery.ts, src/features/room/api/useRoomCategoriesQuery.tsx, src/features/room/api/useRoomQuery.tsx, src/features/room/api/useRoomsQuery.tsx, src/features/user/api/useUsersMeQuery.ts, src/schema/chat.ts, src/schema/index.ts, src/schema/pageMeta.ts, src/schema/room.ts, src/schema/user.ts, src/shared/types/chat.ts, src/shared/types/memoRooms.ts, src/shared/types/pageMeta.ts, src/shared/types/user.ts, src/shared/utils/log.ts, tsconfig.json, yarn.lock
- validation layer를 추가했습니다.(zod를 이용함)
- 이유: 서버에서 응답이 잘못 내려오는 경우를 쉽게 catch하기 위해
=> feat: :sparkles: add zod Schema(서버 응답 스키마 파싱)

src/features/room/components/RoomMemoForm/RoomMemoForm.tsx
https://medium.com/@daveford/prevent-double-click-dups-in-react-83fcbc475704
=> feat: 채팅 전송시 중복 클릭 방지 (디바운스 적용)

src/pages/settings/account/change-password/index.page.tsx
=> feat: :sparkles: 비밀번호 변경페이지 백버튼 추가
